spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # NEW: turn our Order object into JSON text before sending.
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8086          # order-service listens here
